site_name: "axm-fdm-workspace"
site_url: "https://eurocontrol-asu.github.io/axm-fdm-workspace"
repo_url: "https://github.com/eurocontrol-asu/axm-fdm-workspace"

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo

plugins:
  - search
  - monorepo
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          paths: ["packages/*/src"]
          options:
            show_source: true

nav:
  - Home: index.md
